import Image from "next/image";
import { LIGHT_SCRIM } from "./mapPresets";

/**
 * Static hero backdrop — a pre-rendered JPEG of the civic-light preset map
 * (generated by scripts/capture-hero-map.mjs) that REPLACES the live
 * maplibre-gl + deck.gl backdrop on the public landing route.
 *
 * Why: the live map forced ~1.85MB of map JS + a burst of tile fetches into
 * the hero's critical path, so it streamed/janked in well after first paint.
 * The public preset never changes (the chooser is dev-only, gated on ?tweaks),
 * so a single captured plate is pixel-faithful and loads as one fetch.
 *
 * The plate is deliberately STILL — no orbit, no cursor parallax (product
 * call, 2026-07: the map is the stage, not the show). The hero's life comes
 * from MapPinStory instead: report pins plop in one at a time and carry
 * hover cards. This also means the component needs no client JS at all.
 *
 * PLATE_SCALE is kept from the parallax era: every MapPinStory pin position
 * was hand-tuned against the plate rendered at this scale, so removing it
 * would silently shift every pin off its street.
 */
const PLATE_SCALE = 1.16;

export default function StaticHeroMap() {
  return (
    <div
      aria-hidden="true"
      data-hero-bg="map-static"
      className="pointer-events-none absolute inset-0 z-0 overflow-hidden"
    >
      <Image
        src="/landing-shots/hero-map.jpg"
        alt=""
        fill
        // LCP element — priority = eager load + fetchpriority=high, NOT lazy.
        priority
        decoding="async"
        sizes="100vw"
        style={{
          objectFit: "cover",
          transformOrigin: "center",
          transform: `scale(${PLATE_SCALE})`,
        }}
      />

      {/* Scrim — same civic-light gradient the live preset used; kept as a live
          CSS overlay (resolution-independent, seats the wordmark) rather than
          baked into the JPEG. */}
      <div className="absolute inset-0" style={{ background: LIGHT_SCRIM }} />

      {/* Static basemap credit — the live map's attribution badge is stripped
          from the capture, so we restate it here (CARTO Voyager / OSM). */}
      <span
        style={{
          position: "absolute",
          right: 6,
          bottom: 4,
          fontSize: 10,
          lineHeight: 1,
          color: "rgba(40,52,74,0.55)",
          letterSpacing: "0.01em",
        }}
      >
        © CARTO © OpenStreetMap
      </span>
    </div>
  );
}
