import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PrintButton } from "@/components/print-button";
import {
  CATEGORY_META,
  fetchCategoryBreakdown,
  fetchCityStats,
} from "@/lib/dashboard-data";
import { fetchCity } from "@/lib/dashboard-queries";

/* ==================================================================
   Council-meeting report pack (NEXT_100 #51).

   Auto-generates the monthly infrastructure summary a city manager presents to
   council — headline KPIs + category breakdown in a clean, print-to-PDF layout
   (no PDF dependency; the browser's Print dialog does it). Reuses the same
   fetchCityStats / fetchCategoryBreakdown the dashboard uses.
   ================================================================== */

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const city = await fetchCity(slug);
  return { title: city ? `Civic | ${city.name} — Council Report` : "Civic" };
}

export default async function ReportPackPage({ params }: PageProps) {
  const { slug } = await params;
  const city = await fetchCity(slug);
  if (!city) notFound();

  const [stats, breakdown] = await Promise.all([
    fetchCityStats(city.id),
    fetchCategoryBreakdown(city.id),
  ]);

  const resolutionRate =
    stats.total > 0 ? Math.round((stats.resolved / stats.total) * 100) : 0;
  const wow =
    stats.prev_week > 0
      ? Math.round(
          ((stats.this_week - stats.prev_week) / stats.prev_week) * 100,
        )
      : null;

  const kpis: { label: string; value: string }[] = [
    { label: "Total reports", value: String(stats.total) },
    { label: "Open", value: String(stats.open) },
    { label: "Resolved", value: String(stats.resolved) },
    { label: "Resolution rate", value: `${resolutionRate}%` },
    { label: "Avg resolution", value: `${stats.avg_resolution_hours}h` },
    {
      label: "This week",
      value:
        wow == null
          ? String(stats.this_week)
          : `${stats.this_week} (${wow >= 0 ? "+" : ""}${wow}%)`,
    },
  ];

  return (
    <main className="mx-auto w-full max-w-3xl px-6 py-10 text-foreground print:py-0">
      <div className="mb-8 flex items-center justify-between">
        <div>
          <p className="text-[12px] uppercase tracking-[0.08em] text-faint">
            Infrastructure report
          </p>
          <h1 className="text-2xl font-semibold tracking-tight">
            {city.name}, {city.state}
          </h1>
        </div>
        <PrintButton />
      </div>

      <section className="mb-8 grid grid-cols-2 gap-4 sm:grid-cols-3">
        {kpis.map((k) => (
          <div
            key={k.label}
            className="rounded-[var(--radius-lg)] border border-hairline bg-surface p-4"
          >
            <p className="text-[12px] text-faint">{k.label}</p>
            <p className="mt-1 text-[22px] font-semibold tabular-nums">
              {k.value}
            </p>
          </div>
        ))}
      </section>

      <section>
        <h2 className="mb-3 text-[13px] font-medium uppercase tracking-[0.08em] text-faint">
          Reports by category
        </h2>
        <ul className="flex flex-col gap-2">
          {breakdown.map((c) => {
            const meta = CATEGORY_META[c.category] ?? CATEGORY_META.other;
            const pct = stats.total > 0 ? (c.count / stats.total) * 100 : 0;
            return (
              <li key={c.category} className="flex items-center gap-3">
                <span
                  className="h-2.5 w-2.5 flex-shrink-0 rounded-full"
                  style={{ backgroundColor: meta.color }}
                  aria-hidden="true"
                />
                <span className="w-40 flex-shrink-0 text-[13px]">
                  {meta.label}
                </span>
                <span className="h-2 flex-1 overflow-hidden rounded-full bg-overlay">
                  <span
                    className="block h-full rounded-full"
                    style={{ width: `${pct}%`, backgroundColor: meta.color }}
                  />
                </span>
                <span className="w-10 flex-shrink-0 text-right text-[13px] tabular-nums text-subtle">
                  {c.count}
                </span>
              </li>
            );
          })}
        </ul>
      </section>

      <p className="mt-10 text-[12px] text-faint">
        Generated by Civic · Open311 compatible
      </p>
    </main>
  );
}
