// One-shot Vercel deploy for the hosted demo.
//
// Usage:
//   npx vercel login          # once, interactive — only you can do this
//   npx vercel link           # once, pick/create the project
//   node scripts/deploy-vercel.mjs           # push env + deploy preview
//   node scripts/deploy-vercel.mjs --prod    # push env + deploy production
//
// Reads .env.local for the credentials that already work locally, mints the
// two secrets production REFUSES to boot without, pushes every variable to the
// Vercel project, then deploys.
//
// Why a script instead of the dashboard: server env validation throws on a
// missing RATE_LIMIT_TRUSTED_HEADER or PUBLIC_TOKEN_SALT, and demo sign-in
// fails CLOSED without DEMO_COOKIE_SECRET — a judge would get a login form
// that accepts the password and lands nowhere. Setting sixteen variables by
// hand at 11pm is how one of them gets missed.
import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const PROD = process.argv.includes("--prod");
const TARGET = PROD ? "production" : "preview";

if (!existsSync(".env.local")) {
  console.error("no .env.local — copy .env.example and fill it in first");
  process.exit(1);
}

const local = Object.fromEntries(
  readFileSync(".env.local", "utf8")
    .split(/\r?\n/)
    .filter((l) => l && !l.trimStart().startsWith("#") && l.includes("="))
    .map((l) => [l.slice(0, l.indexOf("=")).trim(), l.slice(l.indexOf("=") + 1).trim()]),
);

// Secrets that only matter in production, so .env.local has never needed them.
// Persisted to .env.production.local (gitignored by the leading `.env*` rule)
// so a redeploy reuses the same values — regenerating PUBLIC_TOKEN_SALT would
// invalidate every public /r/<token> status link already handed out.
const GENERATED = ".env.production.local";
const carried = existsSync(GENERATED)
  ? Object.fromEntries(
      readFileSync(GENERATED, "utf8")
        .split(/\r?\n/)
        .filter((l) => l.includes("="))
        .map((l) => [l.slice(0, l.indexOf("=")).trim(), l.slice(l.indexOf("=") + 1).trim()]),
    )
  : {};

function mint(name) {
  if (carried[name]) return carried[name];
  const v = randomBytes(32).toString("base64url");
  carried[name] = v;
  return v;
}

const env = {
  // --- credentials that already work locally ---
  SUPABASE_URL: local.SUPABASE_URL,
  SUPABASE_SERVICE_ROLE_KEY: local.SUPABASE_SERVICE_ROLE_KEY,
  GEMINI_API_KEY: local.GEMINI_API_KEY,
  NEXT_PUBLIC_SUPABASE_URL: local.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: local.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  INTERNAL_CLASSIFY_SECRET: local.INTERNAL_CLASSIFY_SECRET || mint("INTERNAL_CLASSIFY_SECRET"),

  // --- production REFUSES to boot without these two ---
  // Vercel sets x-real-ip itself and strips a client-supplied one, so it is the
  // header the rate limiter can actually trust here.
  RATE_LIMIT_TRUSTED_HEADER: "x-real-ip",
  PUBLIC_TOKEN_SALT: mint("PUBLIC_TOKEN_SALT"),

  // --- without this, demo sign-in fails closed and no persona resolves ---
  DEMO_COOKIE_SECRET: local.DEMO_COOKIE_SECRET || mint("DEMO_COOKIE_SECRET"),

  // --- demo build: seeded corpus, personas, the city a judge will open ---
  NEXT_PUBLIC_DEMO_MODE: "1",
  VIDEO_PIPELINE: local.VIDEO_PIPELINE || "",
};

for (const [k, v] of Object.entries(env)) {
  if (v === undefined || v === "") {
    if (["VIDEO_PIPELINE"].includes(k)) continue;
    console.error(`missing required value: ${k} (set it in .env.local)`);
    process.exit(1);
  }
}

writeFileSync(
  GENERATED,
  `# Generated by scripts/deploy-vercel.mjs. Gitignored. Keep it: regenerating\n` +
    `# PUBLIC_TOKEN_SALT invalidates every public status link already shared.\n` +
    Object.entries(carried).map(([k, v]) => `${k}=${v}`).join("\n") +
    "\n",
);

function vercel(args, input) {
  return execFileSync("npx", ["vercel", ...args], {
    input,
    encoding: "utf8",
    stdio: input === undefined ? "inherit" : ["pipe", "pipe", "pipe"],
    shell: true,
  });
}

console.log(`pushing ${Object.keys(env).length} variables to ${TARGET}\n`);
for (const [k, v] of Object.entries(env)) {
  if (v === "") continue;
  // `env rm` first so a re-run updates instead of erroring on a duplicate.
  try {
    vercel(["env", "rm", k, TARGET, "--yes"], "");
  } catch {}
  try {
    vercel(["env", "add", k, TARGET], v);
    console.log(`  set ${k}`);
  } catch (e) {
    console.error(`  FAILED ${k}: ${String(e.message).split("\n")[0]}`);
  }
}

console.log(`\ndeploying (${TARGET})...`);
vercel(PROD ? ["--prod"] : []);
console.log(
  "\nDone. Before sharing the link, open /api/health — it must report" +
    ' {"database":true,"ai":true}. A missing service key renders pages empty' +
    " and healthy-looking, which is the failure that fools a rehearsal.",
);
