/**
 * Central AI configuration: pure constants + env reads.
 * No side effects, no external imports — safe to import anywhere (client or server).
 */

/** Gemini model used for all classification calls. */
export const GEMINI_MODEL = "gemini-2.5-flash";

/**
 * Per-attempt abort timeout for AI calls, in milliseconds.
 * Bounds the synchronous submit path: worst case ≈ (AI_MAX_RETRIES + 1) *
 * AI_TIMEOUT_MS + backoff. At 20s/1-retry that is ≈ 40s, inside typical
 * serverless function limits — the async path is the real fix for scale.
 */
export const AI_TIMEOUT_MS = 30000;

/**
 * Max retry attempts (beyond the first try) for transient AI failures.
 * Set to 2 (3 attempts total): live Gemini calls intermittently fast-fail on
 * cold serverless instances, and retries (cheap — fast-fails back off in
 * <2s) collapse the per-submit failure rate. Pairs with the route maxDuration.
 */
export const AI_MAX_RETRIES = 2;

/** Base backoff delay in milliseconds; grows exponentially per attempt. */
export const AI_RETRY_BASE_MS = 400;

/** Fixed-window rate limit applied to AI endpoints. */
export const AI_RATE_LIMIT = { windowMs: 60000, max: 20 } as const;

/**
 * When "1", classification runs asynchronously (fire-and-forget / background).
 * Default OFF so the demo path stays synchronous and predictable.
 */
export const ASYNC_CLASSIFY = process.env.NEXT_PUBLIC_ASYNC_CLASSIFY === "1";

/**
 * When "1", the work order's crew/materials/minutes/cost is generated by a
 * second Gemini call (work-order-ai) instead of the deterministic rules table.
 * Default OFF so the synchronous demo path stays fast (one AI call) and
 * predictable; the rules fallback already produces a deterministic est_cost, so
 * a cost number ships either way. When ON, the rules output is the fallback if
 * the AI call fails. Server-only flag (no NEXT_PUBLIC_ prefix).
 */
export const AI_WORK_ORDER = process.env.AI_WORK_ORDER === "1";

/**
 * When "1", the classify pipeline checks each new (non-emergency) report for a
 * duplicate of an earlier open report of the same category within DEDUP_RADIUS_M
 * metres and the last 30 days (via the find_duplicate_report RPC, migration
 * 011). A match marks the new report 'merged', records a merges row, and skips
 * the work order. Default OFF so the demo path always produces a work order and
 * stays predictable. Emergencies are NEVER deduped. Server-only flag.
 */
export const DEDUP_REPORTS = process.env.DEDUP_REPORTS === "1";

/** Geographic radius in metres for duplicate detection. */
export const DEDUP_RADIUS_M = (() => {
  const raw = process.env.DEDUP_RADIUS_M;
  const parsed = raw ? Number(raw) : NaN;
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 50;
})();
