import { existsSync } from "node:fs";
import { join } from "node:path";
import {
  CircleAlert,
  Clock,
  Construction,
  Droplets,
  Footprints,
  HelpCircle,
  Lightbulb,
  type LucideIcon,
  MapPin,
  Signpost,
  SprayCan,
  Trash2,
  TreePine,
  Waves,
} from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CATEGORY_META, KNOWN_CITIES } from "@/lib/dashboard-data";
import { createServerClient } from "@/lib/db/client";
import { getStaffAccessForCity } from "@/lib/staff-access";
import {
  STATUS_LABEL as REPORT_STATUS_LABEL,
  statusChipClass,
} from "@/lib/status";
import type { ReportCategory, ReportStatus } from "@/lib/types";
import { timeAgo } from "@/lib/utils/time-ago";
import { VIDEO_PIPELINE } from "@/lib/video/config";
import { ClusterRowActions, UploadClip } from "./video-console";

// Staff-gated per-request surface (cookies) — never prerender or cache.
export const dynamic = "force-dynamic";

interface PageProps {
  params: Promise<{ slug: string }>;
}

export const metadata: Metadata = {
  title: "Civic | Video damage mapping",
};

interface ClipRow {
  id: string;
  status: string;
  created_at: string;
  frames_sampled: number | null;
  detections_found: number | null;
  error: string | null;
}

interface ClusterRow {
  id: string;
  class: string;
  max_confidence: number;
  frame_count: number;
  status: string;
  decision: string | null;
  decision_rationale: string | null;
  best_detection_id: string | null;
  report_id: string | null;
  merged_report_id: string | null;
}

const STATUS_LABEL: Record<string, string> = {
  candidate: "Candidate",
  escalated: "Needs manual dispatch",
  dispatched: "Dispatched",
  monitoring: "Monitoring",
  dismissed: "Dismissed",
  merged: "Merged",
};

/** A report auto-generated by a dispatch decision, joined to its evidence frame. */
interface GeneratedReport {
  id: string;
  address: string | null;
  description: string | null;
  status: ReportStatus;
  created_at: string;
  category: ReportCategory;
  severity: 1 | 2 | 3 | 4 | 5;
  /** Signed evidence frame from the private bucket, else the public photo. */
  imageUrl: string | null;
}

// Keyed by the kebab `icon` field on CATEGORY_META — same source every other
// surface reads. Re-implemented locally because work-order-grid's copy is
// module-private (and client-only).
const CATEGORY_ICON: Record<string, LucideIcon> = {
  "circle-alert": CircleAlert,
  lightbulb: Lightbulb,
  "sign-post": Signpost,
  "spray-can": SprayCan,
  "trash-2": Trash2,
  droplets: Droplets,
  footprints: Footprints,
  "tree-pine": TreePine,
  construction: Construction,
  waves: Waves,
  "help-circle": HelpCircle,
};

// Mirrors analytics-bento / report-detail SEVERITY_COLORS — same ordinal ramp.
const SEVERITY_COLORS: Record<1 | 2 | 3 | 4 | 5, string> = {
  1: "var(--fg-cyan-burst)",
  2: "var(--color-success)",
  3: "var(--color-warning)",
  4: "var(--fg-neon-coral)",
  5: "var(--color-danger)",
};

function GeneratedReportCard({
  report,
  href,
}: {
  report: GeneratedReport;
  href: string;
}) {
  const meta = CATEGORY_META[report.category];
  const Icon = CATEGORY_ICON[meta.icon] ?? HelpCircle;
  const sevColor = SEVERITY_COLORS[report.severity];

  return (
    <Link
      href={href}
      className="flex gap-3 rounded-[var(--radius-lg)] border border-hairline bg-surface p-3 transition-colors hover:bg-overlay outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-primary)] focus-visible:ring-offset-2 focus-visible:ring-offset-surface"
    >
      <div className="relative h-20 w-28 flex-shrink-0 overflow-hidden rounded-[var(--radius-md)] border border-hairline bg-overlay">
        {report.imageUrl ? (
          // Signed private-bucket frames aren't in next/image remotePatterns —
          // a plain img keeps this staff surface free of config churn.
          // biome-ignore lint/performance/noImgElement: signed one-off URLs
          <img
            src={report.imageUrl}
            alt={`${meta.label} evidence frame`}
            className="h-full w-full object-cover"
          />
        ) : (
          <span className="flex h-full w-full items-center justify-center text-faint">
            <Icon className="h-5 w-5" strokeWidth={1.75} />
          </span>
        )}
      </div>

      <div className="flex min-w-0 flex-1 flex-col gap-1">
        <div className="flex items-center justify-between gap-2">
          <p className="flex min-w-0 items-center gap-2 text-[13px] font-medium text-foreground leading-tight">
            <Icon
              className="h-3.5 w-3.5 flex-shrink-0"
              strokeWidth={2}
              style={{ color: meta.color }}
              aria-hidden
            />
            <span className="truncate">{meta.label}</span>
          </p>
          <div className="flex flex-shrink-0 items-center gap-1.5">
            <span
              className="inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 text-[11px] font-medium text-subtle"
              style={{
                boxShadow: `inset 0 0 0 1px color-mix(in srgb, ${sevColor} 40%, transparent)`,
              }}
            >
              <span
                className="h-1.5 w-1.5 rounded-full"
                style={{ backgroundColor: sevColor }}
                aria-hidden
              />
              Sev {report.severity}
            </span>
            <span
              className={`rounded-md px-1.5 py-0.5 text-[11px] font-medium ${statusChipClass(report.status)}`}
            >
              {REPORT_STATUS_LABEL[report.status]}
            </span>
          </div>
        </div>

        {report.description && (
          <p className="line-clamp-2 text-[12px] text-subtle leading-snug">
            {report.description}
          </p>
        )}

        <div className="mt-auto flex items-center justify-between gap-3 text-[12px] text-faint leading-tight">
          <span className="inline-flex min-w-0 items-center gap-1">
            <MapPin className="h-3 w-3 flex-shrink-0" strokeWidth={1.75} />
            <span className="truncate">{report.address ?? "Unmapped"}</span>
          </span>
          <span className="inline-flex flex-shrink-0 items-center gap-1">
            <Clock className="h-3 w-3" strokeWidth={1.75} />
            {timeAgo(report.created_at)}
          </span>
        </div>
      </div>
    </Link>
  );
}

/**
 * Local demo: the detector's rendered overlay clip, if present. The 42 MB mp4
 * is a gitignored local artifact (public/demo/ — see .gitignore), so this card
 * simply disappears on deploys that don't carry it.
 */
function DemoClipCard() {
  const demoPath = join(process.cwd(), "public", "demo", "civic-demo-clip.mp4");
  if (!existsSync(demoPath)) return null;
  return (
    <section className="rounded-xl border border-border bg-surface p-4">
      <h2 className="mb-1 text-sm font-semibold">Demo clip</h2>
      <p className="mb-3 text-xs opacity-70">
        Sample dashcam pass with the detector&apos;s damage overlays rendered in
        — click play to watch the pipeline&apos;s output. Seed matching table
        rows with <code>node scripts/seed-demo-video.mjs</code>.
      </p>
      {/* biome-ignore lint/a11y/useMediaCaption: synthetic demo footage has no dialogue */}
      <video
        src="/demo/civic-demo-clip.mp4"
        controls
        preload="metadata"
        className="aspect-video w-full rounded-lg border border-border"
      />
    </section>
  );
}

export default async function VideoPipelinePage({ params }: PageProps) {
  const { slug } = await params;
  if (!VIDEO_PIPELINE) notFound();
  const access = await getStaffAccessForCity(slug);
  if (access !== "real") notFound();

  // DB first (provisioned cities), then the KNOWN_CITIES fallback (demo
  // deploy / local dev without a database) — same convention as the team
  // pages. Without a DB row there is no city id, so the tables render empty
  // and uploads fail with a visible error rather than the page 404ing.
  const db = createServerClient();
  const { data: dbCity } = await db
    .from("cities")
    .select("id, name")
    .eq("slug", slug)
    .maybeSingle<{ id: string; name: string }>();
  const known = KNOWN_CITIES[slug];
  if (!dbCity && !known) notFound();
  const city = dbCity ?? { id: null, name: known.name };

  const [{ data: clips }, { data: clusters }] = city.id
    ? await Promise.all([
        db
          .from("video_clips")
          .select(
            "id, status, created_at, frames_sampled, detections_found, error",
          )
          .eq("city_id", city.id)
          .order("created_at", { ascending: false })
          .limit(20),
        db
          .from("video_detection_clusters")
          .select(
            "id, class, max_confidence, frame_count, status, decision, decision_rationale, best_detection_id, report_id, merged_report_id",
          )
          .eq("city_id", city.id)
          .order("created_at", { ascending: false })
          .limit(50),
      ])
    : [{ data: [] }, { data: [] }];

  // Resolve the evidence-frame path of each cluster's best detection so the
  // "View frame" control can mint a signed URL for it.
  const bestIds = ((clusters ?? []) as ClusterRow[])
    .map((c) => c.best_detection_id)
    .filter((id): id is string => !!id);
  const framePathById = new Map<string, string>();
  if (bestIds.length > 0) {
    const { data: dets } = await db
      .from("damage_detections")
      .select("id, frame_path")
      .in("id", bestIds);
    for (const d of (dets ?? []) as { id: string; frame_path: string }[]) {
      framePathById.set(d.id, d.frame_path);
    }
  }

  // Reports generated by dispatch decisions. Read straight off `reports`
  // (not dashboard_reports_view, which drops `description` for PII reasons) —
  // safe here because this page is gated on staff access === "real".
  const clusterRows = (clusters ?? []) as ClusterRow[];
  const reportIds = clusterRows
    .map((c) => c.report_id)
    .filter((id): id is string => !!id);
  const generatedReports: GeneratedReport[] = [];
  if (reportIds.length > 0) {
    const { data: reportRows } = await db
      .from("reports")
      .select(
        "id, address, description, status, created_at, photo_public_url, classifications(category, severity)",
      )
      .in("id", reportIds);

    // The evidence frame lives in the private video-frames bucket; mint a
    // short-lived signed URL per cluster so the card can show the real frame
    // instead of the placeholder photo the seeded report carries.
    const frameUrlByReport = new Map<string, string>();
    await Promise.all(
      clusterRows.map(async (cluster) => {
        if (!cluster.report_id || !cluster.best_detection_id) return;
        const path = framePathById.get(cluster.best_detection_id);
        if (!path) return;
        const { data: signed } = await db.storage
          .from("video-frames")
          .createSignedUrl(path, 600);
        if (signed?.signedUrl)
          frameUrlByReport.set(cluster.report_id, signed.signedUrl);
      }),
    );

    type Classification = { category: string; severity: number };
    type ReportRow = {
      id: string;
      address: string | null;
      description: string | null;
      status: ReportStatus;
      created_at: string;
      photo_public_url: string | null;
      // PostgREST returns a one-to-one embed as an object or a single-element
      // array depending on how it resolves the relationship — handle both.
      classifications: Classification | Classification[] | null;
    };
    const byId = new Map<string, ReportRow>();
    for (const row of (reportRows ?? []) as ReportRow[]) byId.set(row.id, row);
    // Cluster order (newest first) drives card order.
    for (const id of reportIds) {
      const row = byId.get(id);
      if (!row) continue;
      const cls = Array.isArray(row.classifications)
        ? (row.classifications[0] ?? null)
        : row.classifications;
      const category = (cls?.category ?? "other") as ReportCategory;
      generatedReports.push({
        id: row.id,
        address: row.address,
        description: row.description,
        status: row.status,
        created_at: row.created_at,
        category: CATEGORY_META[category] ? category : "other",
        severity: ((cls?.severity ?? 3) as 1 | 2 | 3 | 4 | 5) ?? 3,
        imageUrl: frameUrlByReport.get(row.id) ?? row.photo_public_url ?? null,
      });
    }
  }

  return (
    <main className="mx-auto max-w-5xl space-y-6 p-6">
      <header>
        <h1 className="text-xl font-semibold">
          Video damage mapping — {city.name}
        </h1>
        <p className="mt-1 text-sm opacity-70">
          Clips are scanned by a local detector (no AI-model cost); only
          confident detection clusters trigger an AI decision run, and only
          dispatch decisions create reports.
        </p>
      </header>

      <DemoClipCard />

      <UploadClip slug={slug} />

      <section>
        <h2 className="mb-2 text-sm font-semibold">Recent clips</h2>
        <div className="overflow-x-auto rounded-xl border border-border">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-border">
                <th className="px-3 py-2">Uploaded</th>
                <th className="px-3 py-2">Status</th>
                <th className="px-3 py-2">Frames</th>
                <th className="px-3 py-2">Detections</th>
                <th className="px-3 py-2">Error</th>
              </tr>
            </thead>
            <tbody>
              {((clips ?? []) as ClipRow[]).map((clip) => (
                <tr key={clip.id} className="border-b border-border/50">
                  <td className="px-3 py-2">
                    {new Date(clip.created_at).toLocaleString()}
                  </td>
                  <td className="px-3 py-2">{clip.status}</td>
                  <td className="px-3 py-2">{clip.frames_sampled ?? "—"}</td>
                  <td className="px-3 py-2">{clip.detections_found ?? "—"}</td>
                  <td className="max-w-80 truncate px-3 py-2 text-xs opacity-70">
                    {clip.error ?? ""}
                  </td>
                </tr>
              ))}
              {(clips ?? []).length === 0 && (
                <tr>
                  <td className="px-3 py-3 opacity-70" colSpan={5}>
                    No clips yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </section>

      <section>
        <h2 className="mb-2 text-sm font-semibold">Detection clusters</h2>
        <div className="overflow-x-auto rounded-xl border border-border">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-border">
                <th className="px-3 py-2">Class</th>
                <th className="px-3 py-2">Confidence</th>
                <th className="px-3 py-2">Frames</th>
                <th className="px-3 py-2">Status</th>
                <th className="px-3 py-2">Decision</th>
                <th className="px-3 py-2">Actions</th>
              </tr>
            </thead>
            <tbody>
              {((clusters ?? []) as ClusterRow[]).map((cluster) => (
                <tr
                  key={cluster.id}
                  className="border-b border-border/50 align-top"
                >
                  <td className="px-3 py-2">{cluster.class}</td>
                  <td className="px-3 py-2">
                    {cluster.max_confidence.toFixed(2)}
                  </td>
                  <td className="px-3 py-2">{cluster.frame_count}</td>
                  <td className="px-3 py-2">
                    {STATUS_LABEL[cluster.status] ?? cluster.status}
                    {cluster.report_id && (
                      <div className="text-xs">
                        {/* No per-report detail route exists yet — the grid is
                            the canonical staff surface for dispatched work
                            orders. */}
                        <Link className="underline" href={`/city/${slug}/grid`}>
                          Report →
                        </Link>
                      </div>
                    )}
                  </td>
                  <td className="max-w-96 px-3 py-2 text-xs">
                    {cluster.decision ? (
                      <>
                        <span className="font-medium">{cluster.decision}</span>
                        {cluster.decision_rationale && (
                          <p className="mt-1 opacity-70">
                            {cluster.decision_rationale}
                          </p>
                        )}
                      </>
                    ) : (
                      <span className="opacity-50">—</span>
                    )}
                  </td>
                  <td className="px-3 py-2">
                    <ClusterRowActions
                      slug={slug}
                      clusterId={cluster.id}
                      status={cluster.status}
                      framePath={
                        cluster.best_detection_id
                          ? (framePathById.get(cluster.best_detection_id) ??
                            null)
                          : null
                      }
                    />
                  </td>
                </tr>
              ))}
              {(clusters ?? []).length === 0 && (
                <tr>
                  <td className="px-3 py-3 opacity-70" colSpan={6}>
                    No detections yet — upload a clip above.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </section>

      {reportIds.length > 0 && (
        <section>
          <h2 className="mb-1 text-sm font-semibold">Generated reports</h2>
          <p className="mb-3 text-xs text-subtle">
            Dispatch decisions file a report just like a resident submission —
            the thumbnail is the detector&apos;s evidence frame.
          </p>
          {generatedReports.length > 0 ? (
            <div className="grid gap-2 sm:grid-cols-2">
              {generatedReports.map((report) => (
                <GeneratedReportCard
                  key={report.id}
                  report={report}
                  href={`/city/${slug}/grid`}
                />
              ))}
            </div>
          ) : (
            <p className="rounded-[var(--radius-lg)] border border-hairline bg-surface p-4 text-sm text-subtle">
              No reports yet.
            </p>
          )}
        </section>
      )}
    </main>
  );
}
