/**
 * The report facts block shared by the detections table and the clip theater's
 * rail. Lives in its own module (not page.tsx, which imports `node:fs`) so the
 * client theater can render byte-identical markup.
 */
import {
  CircleAlert,
  Clock,
  Construction,
  Droplets,
  Footprints,
  HelpCircle,
  Lightbulb,
  type LucideIcon,
  MapPin,
  Signpost,
  SprayCan,
  Trash2,
  TreePine,
  Waves,
} from "lucide-react";
import { CATEGORY_META, categoryMeta } from "@/lib/dashboard-data";
import { SEVERITY_HUE } from "@/lib/severity-colors";
import {
  STATUS_LABEL as REPORT_STATUS_LABEL,
  statusChipClass,
} from "@/lib/status";
import type { ReportCategory, ReportStatus } from "@/lib/types";
import { timeAgo } from "@/lib/utils/time-ago";

/** A report auto-generated by a dispatch decision, joined to its evidence frame. */
export interface GeneratedReport {
  id: string;
  address: string | null;
  description: string | null;
  status: ReportStatus;
  created_at: string;
  category: ReportCategory;
  severity: 1 | 2 | 3 | 4 | 5;
  /** Signed evidence frame from the private bucket, else the public photo. */
  imageUrl: string | null;
}

// Keyed by the kebab `icon` field on CATEGORY_META — same source every other
// surface reads. Re-implemented locally because work-order-grid's copy is
// module-private (and client-only).
export const CATEGORY_ICON: Record<string, LucideIcon> = {
  "circle-alert": CircleAlert,
  lightbulb: Lightbulb,
  "sign-post": Signpost,
  "spray-can": SprayCan,
  "trash-2": Trash2,
  droplets: Droplets,
  footprints: Footprints,
  "tree-pine": TreePine,
  construction: Construction,
  waves: Waves,
  "help-circle": HelpCircle,
};

/**
 * Report facts folded inline into a detection row — same chips/typography the
 * standalone report card used, minus its own thumbnail and link wrapper (the
 * row owns both, and nesting a link inside the row's buttons is invalid).
 */
export function ReportInline({
  report,
  clampDescription = true,
}: {
  report: GeneratedReport;
  /** The rail expands the full text; the table row keeps its two-line clamp. */
  clampDescription?: boolean;
}) {
  const meta = categoryMeta(report.category);
  const Icon = CATEGORY_ICON[meta.icon] ?? HelpCircle;
  // Canonical ordinal ramp (src/lib/severity-colors.ts) — the local copy this
  // module used to carry was neither monotonic nor dark-theme correct.
  const sevColor = SEVERITY_HUE[report.severity];

  return (
    <div className="flex min-w-0 flex-col gap-1">
      <div className="flex flex-wrap items-center gap-1.5">
        <p className="flex min-w-0 items-center gap-1.5 text-[13px] font-medium text-foreground leading-tight">
          <Icon
            className="h-3.5 w-3.5 flex-shrink-0"
            strokeWidth={2}
            style={{ color: meta.color }}
            aria-hidden
          />
          <span className="truncate">{meta.label}</span>
        </p>
        <span
          className="inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 text-[11px] font-medium text-subtle"
          style={{
            boxShadow: `inset 0 0 0 1px color-mix(in srgb, ${sevColor} 40%, transparent)`,
          }}
        >
          <span
            className="h-1.5 w-1.5 rounded-full"
            style={{ backgroundColor: sevColor }}
            aria-hidden
          />
          Sev {report.severity}
        </span>
        <span
          className={`rounded-md px-1.5 py-0.5 text-[11px] font-medium ${statusChipClass(report.status)}`}
        >
          {REPORT_STATUS_LABEL[report.status]}
        </span>
      </div>

      {report.description && (
        <p
          className={`text-[12px] text-subtle leading-snug ${clampDescription ? "line-clamp-2" : ""}`}
        >
          {report.description}
        </p>
      )}

      <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[12px] text-faint leading-tight">
        <span className="inline-flex min-w-0 items-center gap-1">
          <MapPin className="h-3 w-3 flex-shrink-0" strokeWidth={1.75} />
          <span className="truncate">{report.address ?? "Unmapped"}</span>
        </span>
        <span className="inline-flex flex-shrink-0 items-center gap-1">
          <Clock className="h-3 w-3" strokeWidth={1.75} />
          {timeAgo(report.created_at)}
        </span>
      </div>
    </div>
  );
}
