-- =============================================================================
-- Civic. Work Order Cost + Source
-- Migration: 20260613_010_work_order_cost.sql
--
-- Additive, safe, idempotent. Adds two nullable columns to work_orders so the
-- classify pipeline can persist an estimated repair cost and record whether the
-- work order's crew/materials/minutes/cost came from the AI generator or the
-- deterministic rules fallback.
--
-- The default synchronous demo path is unaffected: both columns are nullable
-- and written via a SEPARATE guarded update in the pipeline (mirroring
-- classify_status in migration 007), so a database that has NOT applied this
-- migration still completes the core work_orders insert without error.
--
-- NOTE: NOT auto-applied. Run explicitly with:
--   npm run db:migrate
-- Until then the pipeline's cost write is a logged no-op and existing behavior
-- is unchanged.
--
-- Re-runnable: ADD COLUMN IF NOT EXISTS. No data mutated, no behavior changed.
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. est_cost. Estimated total repair cost in whole USD.
--    Deterministic floor = labor_rate * (est_minutes / 60) + material_cost.
--    The AI work-order generator may refine this; null when never computed.
-- ---------------------------------------------------------------------------
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS est_cost numeric;

COMMENT ON COLUMN work_orders.est_cost IS 'Estimated repair cost in USD. Deterministic floor refined by the AI generator when AI_WORK_ORDER=1.';

-- ---------------------------------------------------------------------------
-- 2. wo_source. Provenance of the work order's crew/materials/minutes/cost.
--    'ai'. Generated by the Gemini work-order generator
--    'rules', deterministic rules fallback (AI disabled or AI call failed)
--    null, written before this migration / unknown
-- ---------------------------------------------------------------------------
ALTER TABLE work_orders ADD COLUMN IF NOT EXISTS wo_source text;

COMMENT ON COLUMN work_orders.wo_source IS 'ai|rules|null. Provenance of the work order fields';

COMMIT;
